tasks:

- init: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

- init: |
        brew tap bridgecrewio/tap
        brew install bridgecrewio/tap/yor

- init: mkdir /home/gitpod/.cloudfix-creds
