# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl # runs during prebuild
    command: |
     curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" 
     sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    
  - init: sudo apt-get install jq
  - init: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    command: |
     echo "plugin \"template\"{ enabled = true version = \"0.1.4\" source = \"github.com/trilogy-group/tflint-ruleset-template\" }" > .tflint.hcl
     tflint --init
  - init: >
          curl -s https://github.com/trilogy-group/cloudfix-linter/releases \
          | grep "browser_download_url.*deb" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi -
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

