# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
     sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl 
     curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
     sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" 
     sudo apt update
     sudo apt install terraform
    
  - init: sudo apt-get install jq
  - init: |
        export AWS_ACCESS_KEY_ID=NOTCONFIGURED
        export AWS_SECRET_ACCESS_KEY=NOTCONFIGURED
        export AWS_DEFAULT_REGION=us-west-2
        export AWS_SESSION_TOKEN=NOTCONFIGURED

  - init: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    command: |
     echo "plugin \"template\"{" >> .tflint.hcl
     echo "    enabled = true"  >> .tflint.hcl
     echo "    version = \"0.1.4\"" >> .tflint.hcl
     echo "    source = \"github.com/trilogy-group/tflint-ruleset-template\" " >> .tflint.hcl
     echo "}" >> .tflint.hcl
     tflint --init
  - init: > 
            URL=$(curl -v https://api.github.com/repos/trilogy-group/cloudfix-linter/releases>&1 
            | grep -v ant | grep browser_download_url | grep -v .asc | cut -d '"' -f 4) && wget $URL 
            && ZIP="$(find . -maxdepth 1 -name "namebefore-*-release.zip")" && unzip -qq $ZIP
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

