tasks:

- init: |
    wget https://github.com/trilogy-group/cloudfix-linter/releases/latest/download/install.sh \
      && chmod +x install.sh \
      && ./install.sh
  name: "Setup"    
  command: cloudfix-linter --help 